### ISSUE TITLE
Compile to CommonJS for production

### ISSUE THREAD

**Issue by gaearon** [philholden/subdivide#13]
While the existing build is useful for consumers who need UMD, I think we should create a CommonJS build too by running `babel` over the `src` and putting the result in `lib`. The `main` in `package.json` would then point to `./lib/index.js`. The advantage would be easier debugging and a tree that is easier to understand in React DevTools. Currently Subdivide internal component names are mangled.

**Comment by philholden** [comment]
I agree.

**Comment by philholden** [comment]
Sorry I have broken the build. I have tried to emulate redux-devtoos build. But the lib folder is not getting installed so subdivide can't be found when I install with npm. What am I missing?

**Comment by gaearon** [comment]
I think you need a separate `.npmignore` that is different from `.gitignore`.
You should have `lib` in `.gitignore` but not in `.npmignore`.

**Comment by philholden** [comment]
Thanks

**Comment by philholden** [comment]
should I do: `"jsnext:main": "src/index.js",` too?

**Comment by gaearon** [comment]
Some folks asked for this, so yeah you may wanna do it.
But then make sure you don't have `src` in `.npmignore`.
