### ISSUE TITLE
Latest published release has react-transforms applied

### ISSUE THREAD

**Issue by joshthecoder** [philholden/subdivide#15]
This is causing application production builds to not work since the transformed code
is being pulled in from the subdivide code published to npm.

The npm "build" script should invoke babel with `NODE_ENV=production` set to disable the transform plugins.

**Comment by philholden** [comment]
Hi Josh thanks for letting me know. I have added `NODE_ENV=production` to the build step and published v0.2.2 on npm could you let me know if this works for you and then I will close the issue.

**Comment by joshthecoder** [comment]
Thanks for the fix this should do the trick. :+1:
