### ISSUE TITLE
Please add "React" and "split" words to the repo description for better discoverability

### ISSUE THREAD

**Issue by sompylasar** [philholden/subdivide#16]
Some time ago, I found this library and starred it. Then I forgot its exact name. I wanted to find it by keywords "react" and "split" (these UIs are commonly called "split panes") but could not.

This is a great library and it deserves close-to-first search ranking by "split" and "react" keywords.

**Comment by philholden** [comment]
Thanks I have added these to the keywords. I have also added an iframe safe mode which prevents iframes reloading when previously added panes are deleted.

**Comment by sompylasar** [comment]
@philholden I meant to here: "User defined UI layout: Every pane can be subdivided and any widget assigned to any pane." -- this is the only line besides the repo name that is searchable from GitHub starred UI.

**Comment by sompylasar** [comment]
Could you please also update the GitHub repository description with what you've got in package.json.
Thanks again!

change

> User defined UI layout: Every pane can be subdivided and any widget assigned to any pane.

to

> Split pane layout system for React. Each pane can be subdivided and any widget assigned to any pane allowing users define layout.
